/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

//GtkBuilder *builder = GTK_BUILDER(user_data);


int
main (int argc, char *argv[])
{ GtkBuilder *builder;
  GtkWidget *RHwindowParky;
  GtkWidget *RHwindowAvis_Reclamation;

//builder = gtk_builder_new();

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 /* RHwindowParky = create_RHwindowParky ();
  gtk_widget_show (RHwindowParky);*/
  RHwindowAvis_Reclamation = create_RHwindowAvis_Reclamation ();
  gtk_widget_show (RHwindowAvis_Reclamation);

  gtk_main ();
  return 0;
}
/*
#include <gtk/gtk.h>
#include <stdio.h>

#define FILE_NAME "reclamation.txt"  // Nom du fichier pour enregistrer les réclamations

GError *error = NULL;


// Fonction de rappel pour le clic sur le bouton
static void on_button_clicked(GtkWidget *widget, gpointer data) {
    GtkWidget *entry = GTK_WIDGET(data);  // C'est le widget d'entrée
    const char *reclamation_info = gtk_entry_get_text(GTK_ENTRY(entry));  // Récupérer le texte de l'entrée

    // Ouvrir le fichier en mode ajout
    FILE *file = fopen(FILE_NAME, "a");

    if (file == NULL) {
        // Si le fichier ne peut pas être ouvert, afficher un message d'erreur
        g_print("Erreur lors de l'ouverture du fichier.\n");
    } else {
        // Écrire l'information de la réclamation dans le fichier
        fprintf(file, "Réclamation: %s\n", reclamation_info);
        fclose(file);  // Fermer le fichier

        // Afficher un message de succès
        GtkWidget *dialog = gtk_message_dialog_new(GTK_WINDOW(gtk_widget_get_toplevel(widget)),
                                                   GTK_DIALOG_MODAL,
                                                   GTK_MESSAGE_INFO,
                                                   GTK_BUTTONS_OK,
                                                   "Réclamation enregistrée");
        gtk_dialog_run(GTK_DIALOG(dialog));
        gtk_widget_destroy(dialog);  // Détruire la boîte de dialogue après l'avoir fermée
    }
}

int main(int argc, char *argv[]) {
    GtkBuilder *builder;
    GtkWidget *window;
    GtkWidget *button;
    GtkWidget *entry;

    gtk_init(&argc, &argv);

    // Charger l'interface à partir du fichier .ui (assurez-vous que le chemin du fichier est correct)
     if (gtk_builder_add_from_file(builder, "interface.ui", &error) == 0) {
        g_printerr("Erreur lors du chargement de l'interface : %s\n", error->message);
        g_clear_error(&error);
        return 1;
    }
    // Vérifier si le fichier de l'interface a été chargé avec succès
    if (!builder) {
        g_error("Échec du chargement du fichier de l'interface.");
        return -1;
    }

    // Récupérer la fenêtre, le bouton et l'entrée depuis le builder en utilisant leurs ID
    window = GTK_WIDGET(gtk_builder_get_object(builder, "main_window"));
    button = GTK_WIDGET(gtk_builder_get_object(builder, "my_button"));
    entry = GTK_WIDGET(gtk_builder_get_object(builder, "reclamation_entry"));  // ID de l'entrée

    // Vérifier si la fenêtre, le bouton et l'entrée ont été récupérés avec succès
    if (!window || !button || !entry) {
        g_warning("Certains widgets manquent dans le fichier de l'interface.");
        return -1;
    }

    // Connecter le signal du bouton à la fonction de rappel
    g_signal_connect(button, "clicked", G_CALLBACK(on_button_clicked), entry);

    // Afficher la fenêtre
    gtk_widget_show(window);

    // Lancer la boucle principale de GTK
    gtk_main();

    return 0;
}*/
/*
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include "interface.h"
#include "support.h"

GtkBuilder *builder;

#define FILE_NAME "reclamation.txt"  // Nom du fichier pour enregistrer les réclamations

// Fonction de rappel pour le clic sur le bouton
static void on_button_clicked(GtkWidget *widget, gpointer data) {
    GtkWidget *entry = GTK_WIDGET(data);  // Récupérer le widget d'entrée
    const char *reclamation_info = gtk_entry_get_text(GTK_ENTRY(entry));  // Récupérer le texte

    // Ouvrir le fichier en mode ajout
    FILE *file = fopen(FILE_NAME, "a");

    if (file == NULL) {
        g_print("Erreur : Impossible d'ouvrir le fichier pour l'écriture.\n");
    } else {
        // Écrire la réclamation dans le fichier
        fprintf(file, "Réclamation : %s\n", reclamation_info);
        fclose(file);

        // Afficher un message de succès
        GtkWidget *dialog = gtk_message_dialog_new(GTK_WINDOW(gtk_widget_get_toplevel(widget)),
                                                   GTK_DIALOG_MODAL,
                                                   GTK_MESSAGE_INFO,
                                                   GTK_BUTTONS_OK,
                                                   "Réclamation enregistrée !");
        gtk_dialog_run(GTK_DIALOG(dialog));
        gtk_widget_destroy(dialog);  // Détruire la boîte de dialogue
    }
}

int main(int argc, char *argv[]) {
    GtkWidget *window;
    GtkWidget *button;
    GtkWidget *entry;

    gtk_init(&argc, &argv);

    // Initialiser GtkBuilder et charger l'interface
    builder = gtk_builder_new();
  /*  if (!gtk_builder_add_from_file(builder, "interface.ui", NULL)) {
        g_error("Erreur : Impossible de charger le fichier de l'interface.");
        return -1;
    }*

    // Récupérer les widgets depuis le fichier Glade
    window = GTK_WIDGET(gtk_builder_get_object(builder, "main_window"));
    button = GTK_WIDGET(gtk_builder_get_object(builder, "my_button"));
    entry = GTK_WIDGET(gtk_builder_get_object(builder, "reclamation_entry"));  // ID défini dans Glade

    // Vérifier si les widgets ont été récupérés avec succès
    if (!window || !button || !entry) {
        g_warning("Erreur : Certains widgets manquent dans le fichier de l'interface.");
        return -1;
    }

    // Connecter le signal du bouton au rappel
    g_signal_connect(button, "clicked", G_CALLBACK(on_button_clicked), entry);

    // Connecter les autres signaux définis dans Glade
    gtk_builder_connect_signals(builder, NULL);

    // Afficher la fenêtre principale
    gtk_widget_show(window);

    // Lancer la boucle principale GTK
    gtk_main();

    return 0;
}
*/
